" Bootleg fuzzy-finder + basic settings
set path=.,**
set wildmenu
set ignorecase
set incsearch
set number
set backspace=indent,eol,start
set tabstop=4  softtabstop=4   shiftwidth=4   textwidth=0   expandtab   fileformat=unix
set hidden
set noswapfile
set scrolloff=8
set encoding=utf-8
set splitright
set splitbelow

" Show hard tabs (Ctrl-V + Tab) and trailing whitespaces
set list
set listchars=tab:\⇄\ ,trail:\•
set showbreak="↳ "

" Easier movement between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Copy to clipboard ("+ register works only with gvim installed)
let mapleader = " "
vnoremap <leader>xy :!xclip -f -sel clip<CR>
noremap <leader>xp mz:-1r !xclip -o -sel clip<CR>`z
noremap <leader>y "+y

" Folding
" set foldmethod=indent "for python development indent method is the best. Consider using SimplyFold
set foldmethod=marker " folds are created within {{{ and }}}
set foldlevel=1
set foldlevelstart=1

" Netrw settings
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4

nnoremap <leader>f <Esc>:30vs +Ex<CR>
nnoremap <leader>pv :Ex<CR>

" Surround text in visual mode
" lowercase for separate words within line, uppercase for whole lines
vmap _p <Esc>`>a<CR><Esc>d0`<i<CR><Esc>d0!!surround "("<CR>kJJ
vmap _P :!surround "("<CR>
vmap _b <Esc>`>a<CR><Esc>d0`<i<CR><Esc>d0!!surround "["<CR>kJJ
vmap _B :!surround "["<CR>
vmap _m <Esc>`>a<CR><Esc>d0`<i<CR><Esc>d0!!surround "{"<CR>kJJ
vmap _M :!surround "{"<CR>
vmap _s <Esc>`>a<CR><Esc>d0`<i<CR><Esc>d0!!surround "'"<CR>kJJ
vmap _S :!surround "'"<CR>
vmap _q <Esc>`>a<CR><Esc>d0`<i<CR><Esc>d0!!surround '"'<CR>kJJ
vmap _Q :!surround '"'<CR>

" Plugins {{{
filetype plugin indent on
call plug#begin('~/.vim/plugged')

Plug 'nvie/vim-flake8'
Plug 'tpope/vim-commentary'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-fugitive'
Plug 'vimwiki/vimwiki'
Plug 'itchyny/lightline.vim'
Plug 'hashivim/vim-terraform'
Plug 'mbbill/undotree'
Plug 'morhetz/gruvbox'
Plug 'dracula/vim'


call plug#end()
" }}}

" {{{  Lightline config
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'mode_map': {
        \ 'n' : 'N',
        \ 'i' : 'I',
        \ 'R' : 'R',
        \ 'v' : 'V',
        \ 'V' : 'VL',
        \ "\<C-v>": 'VB',
        \ 'c' : 'C',
        \ 's' : 'S',
        \ 'S' : 'SL',
        \ "\<C-s>": 'SB',
        \ 't': 'T',
        \ },
      \ }

let g:lightline = {
      \ 'colorscheme': 'darcula',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }
" }}}

" {{{ vimwiki config
let g:vimwiki_list = [{'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
let g:vimwiki_markdown_link_ext = 1  " changes vimwiki links from [text](text) to  [text](text.md)
nnoremap <Space><Space> :VimwikiToggleListItem<CR>
noremap <Space>r :VimwikiToggleRejectedListItem<CR>
" }}}

" Colorschemes {{{
" force true color when using regular vim inside tmux:
if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

set termguicolors
set bg=dark
syntax enable
colorscheme dracula
set cursorline
" hi CursorLine term=bold cterm=bold guibg=darkgrey
hi CursorLine term=bold cterm=bold 
hi ColorColumn ctermbg=darkgrey guibg=darkgrey
" }}}

" Other keybingings {{{
map <F8> :setlocal spell! spelllang=en_gb,pl<CR>
map <F1> :colo dracula<CR>
map <F2> :colo gruvbox<CR>
" }}}

