" Bootleg fuzzy-finder + basic settings
set path=.,**
set wildmenu
set ignorecase
set incsearch
set number
set backspace=indent,eol,start
set tabstop=4  softtabstop=4   shiftwidth=4   textwidth=0   expandtab   fileformat=unix
set hidden
set noswapfile
set scrolloff=3
set encoding=utf-8

" Show hard tabs (Ctrl-V + Tab) and trailing whitespaces
set list
set listchars=tab:\⇄\ ,trail:\•
set showbreak="↳ "

" Easier movement between splits
nnoremap <C-J> <C-W><C-J> 
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Copy to clipboard ("+ register works only with gvim installed)
vmap <leader>xy :!xclip -f -sel clip<CR>
map <leader>xp mz:-1r !xclip -o -sel clip<CR>`z
noremap <leader>y "+y

" Folding
" set foldmethod=indent "for python development indent method is the best. Consider using SimplyFold
set foldmethod=marker " folds are created within {{{ and }}}
set foldlevel=1
set foldlevelstart=1

" Netrw settings
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4

map <leader>f <Esc>:30vs +Ex<CR> 

" Plugins {{{
filetype plugin indent on
call plug#begin('~/.vim/plugged')

Plug 'nvie/vim-flake8'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-fugitive'
Plug 'vimwiki/vimwiki'
Plug 'itchyny/lightline.vim'

call plug#end()
" }}}

" {{{  Lightline config
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'mode_map': {
        \ 'n' : 'N',
        \ 'i' : 'I',
        \ 'R' : 'R',
        \ 'v' : 'V',
        \ 'V' : 'VL',
        \ "\<C-v>": 'VB',
        \ 'c' : 'C',
        \ 's' : 'S',
        \ 'S' : 'SL',
        \ "\<C-s>": 'SB',
        \ 't': 'T',
        \ },
      \ }

let g:lightline = {
      \ 'colorscheme': 'darcula',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }
" }}}

" Colorschemes {{{
" set termguicolors
syntax enable
colorscheme slate
set cursorline
" hi CursorLine term=bold cterm=bold guibg=darkgrey
hi CursorLine term=bold cterm=bold 
hi ColorColumn ctermbg=darkgrey guibg=darkgrey
" }}}

" Other keybingings {{{
map <F8> :setlocal spell! spelllang=en_gb,pl<CR>
map <F1> :colo slate<CR>
map <F2> :colo koehler<CR>
nnoremap <Space><Space> :VimwikiToggleListItem<CR>
noremap <Space>r :VimwikiToggleRejectedListItem<CR>
" }}}

" German letters {{{
inoremap <leader>a ä
inoremap <leader>A Ä
inoremap <leader>b ß
inoremap <leader>u ü
inoremap <leader>U Ü
inoremap <leader>o ö
inoremap <leader>O Ö
inoremap <leader>e €
" }}}
