# Destination aliases:
alias tex='cd $HOME/Documents/tex/'
alias proj='cd $HOME/Documents/Projects'
alias tmux='tmux -2'
alias wiki='vim $HOME/vimwiki/index.wiki'
alias gwiki='cd $HOME/vimwiki/'
alias gs='cd $HOME/.vim/snippets'
alias pdf='mupdf'
alias vi='vim -c "let g:tty='\''$(tty)'\''"'
alias vr='vim $HOME/.vim/vimrc'
alias bud='libreoffice $HOME/Documents/Personal/budget.ods'
alias vim='flatpak run org.vim.Vim'
